name: nn_env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10

  # Core scientific stack
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn

  # Deep Learning
  - tensorflow
  - keras
  - pytorch
  - torchvision
  - torchaudio

  # CPU only (remove if using GPU)
  - cpuonly

  # Dev / Experiments
  - jupyter
  - ipykernel
